# Generated by Django 3.1.3 on 2020-11-18 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address2',
            fields=[
                ('user', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('user_name', models.CharField(max_length=30)),
                ('post_code', models.CharField(max_length=10)),
                ('base_address', models.CharField(max_length=100)),
                ('detail_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('user', models.OneToOneField(max_length=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('card_num', models.CharField(max_length=20)),
                ('card_expirantion', models.DateField()),
                ('card_choice', models.CharField(choices=[('KB', '국민카드'), ('SinHan', '신한카드'), ('Samsung', '삼성카드'), ('IBK', '기업은행'), ('KAKAO', '카카오뱅크'), ('BC', '비씨카드'), ('LOTTE', '롯데카드')], max_length=10)),
            ],
        ),
    ]
