# Generated by Django 3.1.3 on 2020-11-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_num', models.IntegerField(db_index=True, unique=True)),
                ('book_name', models.CharField(db_index=True, max_length=30)),
                ('book_stock', models.IntegerField()),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, upload_to='product/%Y/%m/%d')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
