# Generated by Django 3.1.3 on 2020-11-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
