# Generated by Django 3.1.3 on 2020-12-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_choice',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_expirantion',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_num',
        ),
        migrations.AddField(
            model_name='ordertransaction',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
